import { test, expect } from './support/test';
import { fixtureCase, quoteSet, SHARED_CONTEXT } from './support/fixtures';
import { gotoCompare, fillQuoteRow, setCompetitorBaseCents, waitForSettled } from './support/compare-page';
import { resetDemoData } from './support/reset';

/**
 * Pixels assert §3.8's figures just as hard as text does. Earlier specs
 * genuinely consume credit buckets (deadline-expiry books via the API), and
 * the hydrated comparator truthfully paints that state from first paint — so
 * without a reset these screenshots inherit whatever the previous spec left
 * behind and show TC-02's spent-credit numbers against TC-01 baselines.
 * Deterministic state, not looser diffs, is the fix.
 *
 * Top-level, not inside a describe: this file has none — its tests are
 * generated by a viewport loop — which is exactly how the first attempt at
 * this hook silently failed to attach.
 */
// Read-only suite: it needs the fixture to exist in its seeded state, not to
// be rebuilt per worker — the freshness window turns sibling workers' queued
// resets into no-ops instead of rebuilds that race someone else's screenshot.
test.beforeAll(() => resetDemoData({ skipIfFresherThanMs: 120_000 }));

/**
 * §10.1 visual regression: "Playwright screenshots of `/compare` populated,
 * `/claims/[id]`, `/credits` at 390px, 768px and 1440px — in both themes.
 * Eighteen baselines, not nine."
 *
 * Runs on the `desktop` (1440px, light) and `dark` (1440px, dark) Playwright
 * projects (see `playwright.config.ts`), each running once at 390px and once
 * at 768px via `page.setViewportSize` inside the test — so between the two
 * projects and the three sizes below this produces the full light×dark×
 * {390,768,1440} matrix §10.1 asks for.
 *
 * `/claims/[id]` renders its documented not-found/error fallback rather than
 * a populated claim kit whenever `DATABASE_URL` (`playwright.config.ts`) has
 * no database behind it to actually query — which was true for every run in
 * the sandbox this suite was authored in (Docker Hub was unreachable there;
 * see `claim-lifecycle.spec.ts`'s file header). That fallback is still the
 * same component tree real users hit on a stale link, and a genuine baseline
 * worth protecting; the *populated* claim kit is additionally covered,
 * unscreenshotted, by `claim-lifecycle.spec.ts` once a database is reachable.
 *
 * Baselines are intentionally *not* committed by this change. Measured
 * directly against this Playwright version: a missing baseline does **not**
 * pass — `toHaveScreenshot` writes the actual image to
 * `e2e/visual-regression.spec.ts-snapshots/*-<platform>.png` and still fails
 * that run, specifically so "I ran it and it was green" can't mean "I
 * silently created a new baseline nobody looked at." Baselines are also
 * platform-suffixed (`-darwin`, `-linux`, …), so ones generated locally on
 * macOS are never the ones CI's Linux runner would compare against anyway.
 * The correct workflow is: run once per platform, look at the generated
 * image, and commit it deliberately (`git add
 * e2e/visual-regression.spec.ts-snapshots`) once the visual design has
 * stabilized enough to be worth pinning — not something to freeze mid-build
 * while five other agents are still changing `src/components/**`.
 */
const VIEWPORTS = [
  { name: '390', width: 390, height: 844 },
  { name: '768', width: 768, height: 1024 },
  { name: '1440', width: 1440, height: 900 },
] as const;

for (const viewport of VIEWPORTS) {
  test(`/compare populated — ${viewport.name}px`, async ({ page }) => {
    await page.setViewportSize({ width: viewport.width, height: viewport.height });

    const tc01 = fixtureCase('TC-01');
    const q = quoteSet('Q');
    const edit = q.find((row) => row.channel === 'EDIT');
    const fhr = q.find((row) => row.channel === 'FHR');
    if (!edit || !fhr) throw new Error('Quote set Q missing EDIT/FHR');

    await gotoCompare(page);
    await fillQuoteRow(page, 0, edit, { needsAddClick: true });
    await fillQuoteRow(page, 1, fhr, { needsAddClick: true, needsChannelSelect: true });
    await setCompetitorBaseCents(page, Number(SHARED_CONTEXT.competitorBaseCents));
    await waitForSettled(page);
    void tc01; // asserted precisely elsewhere (compare-and-decide.spec.ts); this is a visual snapshot only.

    await expect(page).toHaveScreenshot(`compare-populated-${viewport.name}.png`, {
      fullPage: true,
      animations: 'disabled',
      // The fixed sidebar gets painted at whichever scroll offset the
      // full-page stitcher happened to catch — a documented Playwright quirk
      // with position:fixed, and the one nondeterminism left after the state
      // reset. The nav is not what these baselines guard.
      mask: [page.getByRole('navigation', { name: 'Primary' })],
    });
  });
}

for (const viewport of VIEWPORTS) {
  test(`/claims/[id] (fallback state) — ${viewport.name}px`, async ({ page }) => {
    await page.setViewportSize({ width: viewport.width, height: viewport.height });
    await page.goto('/claims/00000000-0000-0000-0000-000000000000');
    await expect(page).toHaveScreenshot(`claim-kit-fallback-${viewport.name}.png`, {
      fullPage: true,
      // The fixed sidebar gets painted at whichever scroll offset the
      // full-page stitcher happened to catch — a documented Playwright
      // quirk with position:fixed, and the one nondeterminism left after
      // the state reset. The nav is not what these baselines guard.
      mask: [page.getByRole('navigation', { name: 'Primary' })],
    });
  });
}

for (const viewport of VIEWPORTS) {
  test(`/credits — ${viewport.name}px`, async ({ page }) => {
    await page.setViewportSize({ width: viewport.width, height: viewport.height });
    await page.goto('/credits');
    await expect(page).toHaveScreenshot(`credits-${viewport.name}.png`, {
      fullPage: true,
      // The fixed sidebar gets painted at whichever scroll offset the
      // full-page stitcher happened to catch — a documented Playwright
      // quirk with position:fixed, and the one nondeterminism left after
      // the state reset. The nav is not what these baselines guard.
      //
      // "N days" figures are server-rendered from the real clock and count
      // down daily — unmasked, this baseline is stale within 24 hours of
      // being written. Masking the number keeps the layout pinned without
      // pinning today's date. (page.clock can't help: it only freezes the
      // browser's Date, and these strings arrive pre-rendered from the RSC.)
      mask: [page.getByRole('navigation', { name: 'Primary' }), page.getByText(/\d+ days?/)],
    });
  });
}
