import { generateClaimPacket } from '@/domain/claim/claim-packet';
import { EVIDENCE_CHECKLIST, type EvidenceItem } from '@/domain/claim/EvidenceChecklist';
import { CHANNEL_DEFINITIONS } from '@/domain/rules/channels.rules';
import { daysBetween } from '@/domain/shared/Clock';
import { cents } from '@/domain/shared/cents';
import { formatCents } from '@/lib/format';
import { ApiError } from '@/lib/api/errors';
import type { BookingRecord, BookingRepository } from '@/application/ports/BookingRepository';
import type { ClaimRecord, ClaimRepository } from '@/application/ports/ClaimRepository';
import type { CompetingRateRecord, CompetingRateRepository } from '@/application/ports/CompetingRateRepository';
import type { ComparisonRepository } from '@/application/ports/ComparisonRepository';
import type { PropertyRepository } from '@/application/ports/PropertyRepository';
import { QueryUseCase, type ExecutionContext, type UseCaseDependencies } from '../shared/UseCase';

export interface GetClaimPacketInput {
  readonly id: string;
  readonly userId: string;
}

export interface EvidenceChecklistState extends EvidenceItem {
  /**
   * Derived from the data actually on file (the competing rate and the
   * booking), not from a separately-persisted checkbox list — §4.2's schema
   * has no such column, and every one of these ten facts is either present in
   * `competing_rates` already or isn't something the server can know at all
   * (a screenshot's own visual framing, for instance, which the client-side
   * checklist UI still asks the user to confirm).
   */
  readonly satisfied: boolean;
}

export interface GetClaimPacketOutput {
  readonly claim: ClaimRecord;
  readonly text: string;
  readonly checklist: readonly EvidenceChecklistState[];
}

/**
 * `GET /api/claims/:id/packet` — §5.2, §7.4.
 *
 * The claim text itself is generated by `generateClaimPacket` — the pure,
 * tested function in `src/domain/claim/claim-packet.ts` — rather than
 * reimplemented here. This use case's whole job is gathering that function's
 * inputs from three repositories the domain layer cannot reach (a booking has
 * no room type, bed type, or property address of its own in §4.2's schema;
 * the linked comparison and property carry that, when one exists) and
 * injecting `formatCents` from the render layer, exactly as
 * `src/features/claims/ClaimKit.tsx` does on the client — one formatter, one
 * text generator, never forked.
 */
export class GetClaimPacketUseCase extends QueryUseCase<GetClaimPacketInput, GetClaimPacketOutput> {
  public readonly name = 'get_claim_packet';

  constructor(
    deps: UseCaseDependencies,
    private readonly claims: ClaimRepository,
    private readonly bookings: BookingRepository,
    private readonly competingRates: CompetingRateRepository,
    private readonly comparisons: ComparisonRepository,
    private readonly properties: PropertyRepository,
  ) {
    super(deps);
  }

  protected async handle(input: GetClaimPacketInput, _ctx: ExecutionContext): Promise<GetClaimPacketOutput> {
    const claim = await this.claims.findById(input.id, input.userId);
    if (!claim) throw ApiError.notFound('Claim');

    const booking = await this.bookings.findById(claim.bookingId, input.userId);
    if (!booking) throw ApiError.notFound('Booking');

    const competingRate = claim.competingRateId
      ? await this.competingRates.findById(claim.competingRateId)
      : null;

    const comparison = booking.comparisonId
      ? await this.comparisons.findById(booking.comparisonId, input.userId)
      : null;

    const property = comparison?.propertyId ? await this.properties.findById(comparison.propertyId) : null;

    const nights = Math.max(1, daysBetween(new Date(booking.checkIn), new Date(booking.checkOut)));
    const guestCount =
      (competingRate?.adults ?? comparison?.adults ?? 2) + (competingRate?.children ?? comparison?.children ?? 0);

    const text = competingRate
      ? generateClaimPacket({
          hotelName: comparison?.propertyNameSnapshot ?? property?.name ?? 'Hotel name on file with the booking',
          hotelAddress: property?.address ?? 'Address on file — see the original booking confirmation.',
          checkIn: booking.checkIn,
          checkOut: booking.checkOut,
          roomType: competingRate.roomType ?? comparison?.roomType ?? 'Not specified',
          bedType: competingRate.bedType ?? comparison?.bedType ?? 'Not specified',
          guestCount,
          currency: competingRate.currency ?? comparison?.currency ?? 'USD',
          cancellationPolicy: booking.refundable
            ? 'Fully refundable per the original booking terms.'
            : 'Non-refundable per the original booking terms.',
          nights,
          bookingChannelLabel: CHANNEL_DEFINITIONS[booking.channel].label,
          ownTotalCents: booking.totalCents,
          ownBaseCents: booking.baseCents,
          competitorSiteDomain: competingRate.siteDomain,
          competitorUrl: competingRate.url,
          competitorBaseCents: competingRate.baseCents,
          competitorTotalCents:
            competingRate.taxCents !== null ? cents(competingRate.baseCents + competingRate.taxCents) : null,
          formatMoney: formatCents,
        })
      : 'No competing rate is on file yet — add one via POST /api/claims/:id/evidence before generating the claim text.';

    return {
      claim,
      text,
      checklist: EVIDENCE_CHECKLIST.map((item) => ({
        ...item,
        satisfied: isSatisfied(item.id, booking, competingRate),
      })),
    };
  }
}

function isSatisfied(
  itemId: string,
  booking: BookingRecord,
  rate: CompetingRateRecord | null,
): boolean {
  if (!rate) return false;
  switch (itemId) {
    case 'full_url':
      return rate.url.trim().length > 0;
    case 'visible_clock':
      return rate.capturedAt !== null;
    case 'hotel_identity':
      return rate.siteDomain.trim().length > 0;
    case 'dates':
      return Boolean(booking.checkIn && booking.checkOut);
    case 'occupancy':
      return rate.adults !== null;
    case 'room_and_bed':
      return rate.roomType !== null && rate.bedType !== null;
    // §7.4's highest-risk item: a cheaper non-refundable rate never matches a
    // refundable booking. Satisfied only when the cancellation terms agree.
    case 'cancellation_policy':
      return rate.refundable === booking.refundable;
    case 'base_rate':
      return rate.baseCents > 0;
    case 'taxes_itemised':
      return rate.taxCents !== null;
    // The other highest-risk item — publicly available *and* the currency is
    // on record, since an uncaptured currency can't be verified as public.
    case 'public_rate':
      return rate.publiclyAvailable === true && rate.currency !== null;
    default:
      return false;
  }
}
